language: go
go:
  - "1.10"
before_install:
  - go get github.com/golang/lint/golint
  - go get honnef.co/go/tools/cmd/unused
  - go get honnef.co/go/tools/cmd/staticcheck
script:
  - make all
  - make cross
